### ISSUE TITLE
[DefaultBreadcrumb("ViewData.Title")] just displays "ViewData.Title" and not the title itself?

### ISSUE THREAD

**Issue by mikeym88** [zHaytam/SmartBreadcrumbs#19]
I'm setting the default breadcrumb using: `[DefaultBreadcrumb("ViewData.Title")]` but that just displays the "ViewData.Title" and not the title itself (e.g. Home). Is there a way to set the default breadcrumb title based on the actual title?

**Comment by zHaytam** [comment]
If you see `ViewData.Title` that means it's not set, can you please make sure it's set?
For example: `ViewData["Title"] = "Home";` in your page.

**Comment by mikeym88** [comment]
I tried putting `ViewData["Title"] = "Home";` in the View and in the action. Neither seems to work.

**Comment by zHaytam** [comment]
If your project is new/simple, would you like to upload it to me or tell me how to reproduce the problem?

**Comment by mikeym88** [comment]
I created a new project for this: https://github.com/mikeym88/DefaultBreadcrumbBug

**Comment by zHaytam** [comment]
Hi, sorry for the huge delay.
I fixed the issue.
The update will be available soon in Nuget, version 1.0.5.1.

However, you will still have a problem where the home page menu will have the same title as the others since you're not caching it, so it's taking the current ViewData.Title which is the other pages' titles.
