### ISSUE TITLE
V2 - No docs about manual nodes

### ISSUE THREAD

**Issue by imukai** [zHaytam/SmartBreadcrumbs#22]
So I made the possible mistake up upgrading to the new version which has caused all of my manual BreadcrumbNode creations to fail with an error about being unable to create an instance of an abstract class or interface.

Is there a document on how to upgrade from your old version to this newer version?  I looked through the readme and the wiki to no avail.

**Comment by zHaytam** [comment]
Hello, as this version contains breaking changes issues like that are a normal thing. Sorry that the Wiki doesn't contain that part, I didn't write it yet :/

In v2, there are two types of nodes: `RazorPageBreadcrumbNode` and `MvcBreadcrumbNode` (see https://github.com/zHaytam/SmartBreadcrumbs/tree/master/src/Nodes) so you should be creating these instead of the old one.

I made things this way to give the possibility to mix MVC actions with Razor Pages, as such, the arguments needed for each one are different. Hope this helps!

**Comment by imukai** [comment]
Understood -- I'm guilty of documentation neglect myself so I'm not dinging you on it, just mainly wanted to ask in case I was missing where it was hiding.

I'd reverted back to 1.x for the time being but later today I'll try 2 again and see if I can get one of the newer node types to work.  Will let you know.  :)

**Comment by zHaytam** [comment]
I wrote a little page about manual pages, you can check it out here: https://github.com/zHaytam/SmartBreadcrumbs/wiki/4.-Manual-nodes

If you still have a problem, please re-open (if it's about the docs) or create a new issue :')
