### ISSUE TITLE
Razor Pages - Passing Ids into breadcrumb so links work actions

### ISSUE THREAD

**Issue by DivineLawnmower** [zHaytam/SmartBreadcrumbs#39]
Hi,

I have been attempting to implement your breadcrumbing solution into a Razor page - based solution. Any pages where no route-params are required works great. However, when we pass asp-route-<ids> between pages I cannot for the life of me work out how to implement your solution.

I read that you can manually create child nodes: 

```
var childNode3 = new RazorPageBreadcrumbNode("/Path", "ViewData.Something")
{
	OverwriteTitleOnExactMatch = true,
	Parent = childNode2
};

// Tell SmartBreadcrumbs to use them;
// PS: Use the last created node.
ViewData["BreadcrumbNode"] = childNode3;
```
However, this clears the entire breadcrumb route I had previously and I still cannot get the Ids to pass through so the page either doesn't redirect and/or gets caught in missing id error handling.

Is it possible to get some sort of explanation or example such that I could implement breadcrumbing as below:
https://i.gyazo.com/36b40fd7fd9c842a2b0b428c2d6244e7.png

Where the breadcrumbs could be passed one or more Ids? e.g. Forms page, select a form -> formVersion page, select a formVersion -> you then have two pages that require working link breadcrumbs, one requiring a formId, one requiring both a formId and formVersionId, etc

Kind regards,
Matt

**Comment by zHaytam** [comment]
Hello Matt, thank you for opening an issue.
First, what do you mean by "this clears the entire breadcrumb route"? do you mean that it only displays one node?
Second, I don't see in your code the ids being passed, shouldn't it be `/Path/{Id}`?

If you're working with params, did you try `RouteValues`?

**Comment by thebigcrab** [comment]
Hi,

Not the author of this issue but believe I am having a very similar (likely the same) issue. 

So in my example I have about 5 levels of entities - the details aren't that relevant but the top 3 are Page -> Section Group -> Section

I don't actually have a "list" view for Section Group or Section (in other words if a user was to go to /SectionGroup/ they would get a 404 error meanwhile going to /SectionGroup/1 would show details of the Section Group with ID of 1. 

The way this works in practice is a user chooses a page and is displayed a list of Section Groups that page contains, then they choose a Group and are shown a list of Sections that this chosen Group contains and so on. The problem with the default implementation is once on a Section - instead of the breadcrumb linking to the parent Section Group (in this case /SectionGroup/1) it instead tries to link to /SectionGroup and hence ends up on a 404 page.

I suspect (optimistically hope :p) that you can do this already but perhaps it is something that could be more clearly explained in the Wiki section. 

Really appreciate your help with this 👍 

Louis

**Comment by zHaytam** [comment]
Hello Louis, I believe it is the same "issue" (and I use quotes because I believe the solution is already implemented).

In order to make sure, can you provide the code you use to create the nodes?

**Comment by thebigcrab** [comment]
Hey there,

I thought it would be!

Sure thing - so I set my top level breadcrumb to the controller

[DefaultBreadcrumb("Report Wizard")]
public class ReportWizard : Controller

Then the Page...
[Breadcrumb("Page")]
public async Task<IActionResult> Page(int? id)

Section Group...
[Breadcrumb("Section Group", FromAction = "Page", FromController = typeof(ReportWizard) )]
public async Task<IActionResult> SectionGroup(int? id)

etc

Hope this helps clarify :)

Thanks,
Louis

**Comment by zHaytam** [comment]
Id you use attributes, it's impossible to know the value of the Id to add it to links, since it changes depending on whatever factor.

This is why I created Manual Nodes (see wiki), for scenarios like these.


Example:
Home > Parent Category > SubCategory > Product
This redults in 4 nodes and the categories have an Id that you pass using `RouteValues`.

**Comment by thebigcrab** [comment]
Makes a lot of sense - had misunderstood how the Manual Nodes worked previously but I think this fixes the issue for me thanks!

L

**Comment by thebigcrab** [comment]
So the above works (really well actually) but as a slight aside question you say in the Wiki...

// Manually create the nodes (assuming you used the attribute
// to create a Default node, otherwise create it manually too).

But I'm not sure how you specify a node as being the Default when creating them manually. It's not really a deal breaker but in my scenario we only want the breadcrumbs on specific parts of the site - it also seems like it would be difficult to have 2 sets of breadcrumbs with different roots (again unless you can somehow specify the root manually).

This may be better served as a feature request instead as more comments to an issue which is arguably solved!

**Comment by zHaytam** [comment]
What I meant by that comment is, if you have a `DefaultBreadcrumb` it will always be added at the end of your manual nodes.

What I didn't include in the Wiki is that you can change that behaviour using `DontLookForDefaultNode` in the BreadcrumbOptions (services).

If you set it to true, then the default breadcrumb will be ignored when using manual nodes (or if you don't have a default node), then you can include a node at the start of your manual nodes so that it acts as "default".

**Comment by zHaytam** [comment]
I assume that you fixed your issue @DivineLawnmower, so I'm closing the issue.  
Feel free to re-open if you still have it thought!
