### ISSUE TITLE
Most recent version breaks breadcrumb rendering...

### ISSUE THREAD

**Issue by markchipman** [zHaytam/SmartBreadcrumbs#67]
I updated my project from using 3.4.0 to 3.5.0 (that being the only change I performed).  Everything compiles fine... however I get the following runtime error that throws an error:

![image](https://user-images.githubusercontent.com/4852240/88984061-e1457700-d289-11ea-8af3-ad6112afb022.png)

Not sure what you changed in the last update, but something is awry.

**Comment by zHaytam** [comment]
This is weird, since route values (the dictionary) contains the key `page` with value `null` when you're visiting an action in a controller and not a Razor page, but in your case it doesn't.

Can you tell me when does the exception fire exactly? What are you visiting etc... This can be an easy fix but it would be better to know why it happens first.  
Thanks!

**Comment by manisto** [comment]
I'm having a similar issue, only with areas not being present. It is the only thing we have changed. I'm not using areas, and currently have no need to do so.

![firefox_V10WEygvuB](https://user-images.githubusercontent.com/188267/89020882-f0770400-d31f-11ea-811d-9f2d092253d0.png)

**Comment by zHaytam** [comment]
Ah, maybe because you don't even enable Blazor pages and Areas that the keys aren't present. I will try a fix asap.

**Comment by zHaytam** [comment]
I believe it's now fixed in 3.5.1 (NuGet will be available shortly).  
If you still see the issue, please re-open.

**Comment by markchipman** [comment]
Just wanted to let you know that the new fix worked!  Thanks for your prompt resolution to the issue 👍
