### ISSUE TITLE
Isn't rendering previous section.

### ISSUE THREAD

**Issue by dlagg** [zHaytam/SmartBreadcrumbs#75]
My Index breadcrumb is working with this directive:
`[Breadcrumb("Documentos", AreaName = "Admin", FromAction = "Index", FromController = typeof(WorkersController))]`
But my Create breadcrumb view which is referencing Index/<WorkerId> , doesn't works:
```csharp
MvcBreadcrumbNode childNode = new MvcBreadcrumbNode("Index", "WorkersDocument",
                "Subir Documento", true, null, null)
            {
                RouteValues = new { id },
            };

            ViewData["BreadcrumbNode"] = childNode; 
```
Is rendered only the title tag, no previous link to Index.

**Comment by zHaytam** [comment]
You aren't referencing the Index breadcrumb here, you're only creating 1 breadcrumb with points to "Index" in "WorkersDocument". In order to do what you want, you will need to either:

1. Create 2 breadcrumb nodes, one for index and the other for create (where its `Parent` is the index node)
2. Get the index node from `BreadcrumbsManager` and set `childNode`'s `Parent` to it.

Hope this helps!

**Comment by dlagg** [comment]
> You aren't referencing the Index breadcrumb here, you're only creating 1 breadcrumb with points to "Index" in "WorkersDocument". In order to do what you want, you will need to either:
> 
> 1. Create 2 breadcrumb nodes, one for index and the other for create (where its `Parent` is the index node)
> 2. Get the index node from `BreadcrumbsManager` and set `childNode`'s `Parent` to it.
> 
> Hope this helps!

Can I use MvcBreadcrumbNode object with Breadcrumb attributes? Seems I need to change all my paths to MvcBreadcrumbNode and link them to _Parent_ prop. but they works well with attributes.

**Comment by zHaytam** [comment]
You can't since you're setting `RouteValues` and the `id` is only available inside the method (action), so the 2 solutions above are the only possibilities. You don't need to convert all your actions to use `MvcBreadcrumbNode`, only create nodes manually when you want to dynamically fill `RouteValues`, the other pages can still use the attributes normally.

**Comment by zHaytam** [comment]
I hope you found a solution, if not, feel free to re-open!
